### ISSUE TITLE
About Deterministic Builds

### ISSUE THREAD

**Issue by HavenDV** [Turnerj/dotnet-library-checklist#5]
Hello. I stumbled upon this repository by accident, it was interesting to read it!

https://github.com/Turnerj/dotnet-library-checklist#enable-deterministic-builds
I want to note the moment with `<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>` - it is worth pointing out that this should only be active at the time of the build in the CI environment. Here's why:
https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/#deterministic-builds

> While deterministic builds are enabled by default in .NET SDK projects, there is an extra property, ContinuousIntegrationBuild, to set on the build server to normalize stored file paths. These should not be enabled during local dev or the debugger won’t be able to find the local source files.

**Comment by Turnerj** [comment]
Good catch! I've updated the documentation to reflect that and link off to that specific blog post.

Cheers mate!
